# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Stile codice
    - prefer_single_quotes
    - prefer_final_locals
    - require_trailing_commas
    - sort_constructors_first
    - avoid_redundant_argument_values
    - avoid_catches_without_on_clauses
    - avoid_print
    - avoid_shadowing_type_parameters
    - cancel_subscriptions
    - close_sinks
    - depend_on_referenced_packages
    - unnecessary_overrides
    - unnecessary_parenthesis
    - use_super_parameters
    - valid_regexps

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
