display_name: MyPlaylist
package_name: my-playlist
version: 3.12.3+1
maintainer:
  name: Massimo
  email: massimo@example.com
architecture: amd64
installed_size: 0
priority: optional
section: utils
icon: assets/logo.png
depends:
  - libgtk-3-0
  - libjson-cpp25
  - libsecret-1-0
  - ffmpeg
  - mkvtoolnix
  - gpac
description: |-
  Professional video playlist manager with smart metadata synchronization (TMDB), 
  FFmpeg integration, and remote control support.
